-- src/sql/opensim/create_regions.sql
-- OpenSim regions table
CREATE TABLE IF NOT EXISTS regions (
    uuid VARCHAR(36) NOT NULL PRIMARY KEY,
    region_name VARCHAR(128) DEFAULT NULL,
    region_recv_key VARCHAR(128) DEFAULT NULL,
    region_send_key VARCHAR(128) DEFAULT NULL,
    region_secret VARCHAR(128) DEFAULT NULL,
    region_data_uri VARCHAR(255) DEFAULT NULL,
    server_ip VARCHAR(64) DEFAULT NULL,
    server_port INTEGER DEFAULT NULL,
    server_uri VARCHAR(255) DEFAULT NULL,
    loc_x INTEGER DEFAULT NULL,
    loc_y INTEGER DEFAULT NULL,
    loc_z INTEGER DEFAULT NULL,
    east_override_handle BIGINT DEFAULT NULL,
    west_override_handle BIGINT DEFAULT NULL,
    south_override_handle BIGINT DEFAULT NULL,
    north_override_handle BIGINT DEFAULT NULL,
    region_asset_uri VARCHAR(255) DEFAULT NULL,
    region_asset_recv_key VARCHAR(128) DEFAULT NULL,
    region_asset_send_key VARCHAR(128) DEFAULT NULL,
    region_user_uri VARCHAR(255) DEFAULT NULL,
    region_user_recv_key VARCHAR(128) DEFAULT NULL,
    region_user_send_key VARCHAR(128) DEFAULT NULL,
    region_map_texture VARCHAR(36) DEFAULT NULL,
    server_http_port INTEGER DEFAULT NULL,
    server_remote_admin_port INTEGER DEFAULT NULL,
    scope_id VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    size_x INTEGER NOT NULL DEFAULT 256,
    size_y INTEGER NOT NULL DEFAULT 256,
    flags INTEGER NOT NULL DEFAULT 0,
    last_seen BIGINT NOT NULL DEFAULT 0,
    parcel_map_texture VARCHAR(36) DEFAULT NULL
);