-- src/sql/opensim/create_primitives.sql
-- OpenSim primitives (scene objects) table
CREATE TABLE IF NOT EXISTS primitives (
    uuid VARCHAR(36) NOT NULL,
    region_uuid VARCHAR(36) DEFAULT NULL,
    creation_date INTEGER DEFAULT NULL,
    name VARCHAR(255) DEFAULT NULL,
    scene_group_id VARCHAR(36) DEFAULT NULL,
    text VARCHAR(255) DEFAULT NULL,
    description VARCHAR(255) DEFAULT NULL,
    sit_name VARCHAR(255) DEFAULT NULL,
    touch_name VARCHAR(255) DEFAULT NULL,
    object_flags INTEGER DEFAULT NULL,
    creator_id VARCHAR(36) DEFAULT NULL,
    owner_id VARCHAR(36) DEFAULT NULL,
    group_id VARCHAR(36) DEFAULT NULL,
    last_owner_id VARCHAR(36) DEFAULT NULL,
    owner_mask INTEGER DEFAULT NULL,
    next_owner_mask INTEGER DEFAULT NULL,
    group_mask INTEGER DEFAULT NULL,
    everyone_mask INTEGER DEFAULT NULL,
    base_mask INTEGER DEFAULT NULL,
    position_x DOUBLE DEFAULT NULL,
    position_y DOUBLE DEFAULT NULL,
    position_z DOUBLE DEFAULT NULL,
    group_position_x DOUBLE DEFAULT NULL,
    group_position_y DOUBLE DEFAULT NULL,
    group_position_z DOUBLE DEFAULT NULL,
    velocity_x DOUBLE DEFAULT NULL,
    velocity_y DOUBLE DEFAULT NULL,
    velocity_z DOUBLE DEFAULT NULL,
    angular_velocity_x DOUBLE DEFAULT NULL,
    angular_velocity_y DOUBLE DEFAULT NULL,
    angular_velocity_z DOUBLE DEFAULT NULL,
    acceleration_x DOUBLE DEFAULT NULL,
    acceleration_y DOUBLE DEFAULT NULL,
    acceleration_z DOUBLE DEFAULT NULL,
    rotation_x DOUBLE DEFAULT NULL,
    rotation_y DOUBLE DEFAULT NULL,
    rotation_z DOUBLE DEFAULT NULL,
    rotation_w DOUBLE DEFAULT NULL,
    sit_target_offset_x DOUBLE DEFAULT NULL,
    sit_target_offset_y DOUBLE DEFAULT NULL,
    sit_target_offset_z DOUBLE DEFAULT NULL,
    sit_target_orient_w DOUBLE DEFAULT NULL,
    sit_target_orient_x DOUBLE DEFAULT NULL,
    sit_target_orient_y DOUBLE DEFAULT NULL,
    sit_target_orient_z DOUBLE DEFAULT NULL,
    regent_uuid VARCHAR(36) DEFAULT NULL,
    click_action TINYINT(4) DEFAULT NULL,
    material TINYINT(4) DEFAULT NULL,
    collision_sound VARCHAR(36) DEFAULT NULL,
    collision_sound_volume DOUBLE DEFAULT NULL,
    link_number INTEGER DEFAULT NULL,
    PRIMARY KEY (uuid),
    KEY region_uuid (region_uuid),
    KEY scene_group_id (scene_group_id)
);