-- src/sql/opensim/create_parcels.sql
-- OpenSim land/parcels table
CREATE TABLE IF NOT EXISTS land (
    uuid VARCHAR(36) NOT NULL,
    region_uuid VARCHAR(36) DEFAULT NULL,
    local_land_id INTEGER DEFAULT NULL,
    bitmap LONGBLOB DEFAULT NULL,
    name VARCHAR(255) DEFAULT NULL,
    description VARCHAR(255) DEFAULT NULL,
    owner_uuid VARCHAR(36) DEFAULT NULL,
    is_group_owned BOOLEAN DEFAULT NULL,
    area INTEGER DEFAULT NULL,
    auction_id INTEGER DEFAULT NULL,
    category TINYINT(4) DEFAULT NULL,
    claim_date INTEGER DEFAULT NULL,
    claim_price INTEGER DEFAULT NULL,
    group_uuid VARCHAR(36) DEFAULT NULL,
    sale_price INTEGER DEFAULT NULL,
    land_status TINYINT(4) DEFAULT NULL,
    land_flags INTEGER DEFAULT NULL,
    land_type TINYINT(4) DEFAULT NULL,
    media_auto_scale TINYINT(4) DEFAULT NULL,
    media_texture_uuid VARCHAR(36) DEFAULT NULL,
    media_url VARCHAR(255) DEFAULT NULL,
    music_url VARCHAR(255) DEFAULT NULL,
    pass_hours DOUBLE DEFAULT NULL,
    pass_price INTEGER DEFAULT NULL,
    snapshot_uuid VARCHAR(36) DEFAULT NULL,
    user_location_x DOUBLE DEFAULT NULL,
    user_location_y DOUBLE DEFAULT NULL,
    user_location_z DOUBLE DEFAULT NULL,
    user_look_at_x DOUBLE DEFAULT NULL,
    user_look_at_y DOUBLE DEFAULT NULL,
    user_look_at_z DOUBLE DEFAULT NULL,
    auth_buyer_id VARCHAR(36) DEFAULT '00000000-0000-0000-0000-000000000000',
    other_clean_time INTEGER DEFAULT NULL,
    dwell INTEGER DEFAULT 0,
    media_type VARCHAR(32) DEFAULT 'none/none',
    media_description VARCHAR(255) DEFAULT '',
    media_size VARCHAR(16) DEFAULT '0,0',
    media_loop BOOLEAN DEFAULT FALSE,
    obscure_music BOOLEAN DEFAULT FALSE,
    obscure_media BOOLEAN DEFAULT FALSE,
    see_av1 DOUBLE DEFAULT NULL,
    see_av2 DOUBLE DEFAULT NULL,
    environment TEXT DEFAULT NULL,
    PRIMARY KEY (uuid),
    KEY region_uuid (region_uuid)
);

CREATE TABLE IF NOT EXISTS landaccesslist (
    land_uuid VARCHAR(36) DEFAULT NULL,
    access_uuid VARCHAR(36) DEFAULT NULL,
    flags INTEGER DEFAULT NULL,
    expires INTEGER DEFAULT NULL,
    KEY land_uuid (land_uuid)
);